import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { load } from 'js-yaml'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

// Inline the Zod schema here to avoid circular imports in the build script
import { z } from 'zod'

const skillItemSchema = z.object({
  name: z.string(),
  level: z.number().min(0).max(100).optional(),
})

const skillCategorySchema = z.object({
  name: z.string(),
  icon: z.string(),
  items: z.array(skillItemSchema),
})

const projectSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string(),
  tags: z.array(z.string()),
  github: z.string(),
  demo: z.string(),
  status: z.enum(['completed', 'in-progress', 'placeholder']),
  featured: z.boolean(),
})

const testSuiteSchema = z.object({
  id: z.string(),
  label: z.string(),
  spec_pattern: z.string(),
})

const siteConfigSchema = z.object({
  personal: z.object({
    name: z.string(),
    title: z.string(),
    tagline: z.string(),
    email: z.string(),
    location: z.string().optional(),
    avatar: z.string().optional(),
  }),
  social: z.object({
    github: z.string().optional(),
    linkedin: z.string().optional(),
    twitter: z.string().optional(),
    youtube: z.string().optional(),
  }),
  resume: z.object({
    url: z.string(),
    label: z.string(),
  }),
  about: z.object({
    bio: z.string(),
    highlights: z.array(z.string()),
  }),
  skills: z.object({
    categories: z.array(skillCategorySchema),
  }),
  projects: z.array(projectSchema),
  test_runner: z.object({
    enabled: z.boolean(),
    title: z.string(),
    description: z.string(),
    default_suite: z.string(),
    available_suites: z.array(testSuiteSchema),
  }),
})

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Support: local dev (scripts/ → ../../config.yaml) or Docker (/app/config.yaml)
const configPath = process.env.CONFIG_PATH
  ?? join(__dirname, '../../config.yaml')
const outputDir = join(__dirname, '../src/generated')
const outputPath = join(outputDir, 'config.ts')

console.log('Reading config from:', configPath)

const yaml = readFileSync(configPath, 'utf-8')
const raw = load(yaml)

const result = siteConfigSchema.safeParse(raw)
if (!result.success) {
  console.error('config.yaml validation failed:')
  console.error(JSON.stringify(result.error.flatten().fieldErrors, null, 2))
  process.exit(1)
}

mkdirSync(outputDir, { recursive: true })

const output = `// AUTO-GENERATED — do not edit this file directly.
// Edit config.yaml at the project root and run \`npm run build:config\`.
import type { SiteConfig } from '../types/config'

const config: SiteConfig = ${JSON.stringify(result.data, null, 2)} as const

export default config
`

writeFileSync(outputPath, output, 'utf-8')
console.log('Config generated successfully at:', outputPath)
